### ISSUE TITLE
problem in multiple user and connection pool

### ISSUE THREAD

**Issue by vermaslal** [baudehlo/Haraka#1017]
I have created two users:- user1 and user2

Started sending mail with connection pooling with below setting in nodemailer (nodemailer-smtp-pool)

greetingTimeout: 90000
connectionTimeout: 30000
maxConnections: 100
maxMessages: 500

when simultaneously run two file with user1 and user2, it send user1's mails first

**Comment by smfreegard** [comment]
You need to explain this problem better.  I don't understand what you think the problem is with Haraka (and why it isn't a nodemailer issue).

**Comment by vermaslal** [comment]
Please help in finding problem.

When I create new SMTP connection for each mail it sends correctly for both user.

And when I use SMTP pool it holds sending mail for second user while first user is almost done.

In both cases  I am getting response like "250 Message Queued (769337FE-5F8C-4CBC-A3BF-04CDC453B9BE.1)"

**Comment by smfreegard** [comment]
> And when I use SMTP pool it holds sending mail for second user while first user is almost done.

Sounds like an issue with nodemailer-smtp-pool and how it's sending the mail rather than anything to do with Haraka.

Haraka will send whatever it is given by the client; it doesn't decide the order that mail is sent.   It's up to you to find out why that is - if you can show an issue with Haraka, then we'll gladly look at it.
