### ISSUE TITLE
Inbound whitelist ip-address

### ISSUE THREAD

**Issue by TellusTalk** [baudehlo/Haraka#620]
Hi!
I'm trying to whitelist ip-addresses! But I can't get it to work.

The idea was
domain.com (blacklist)
234.543.1.1 (whitelist domain.com's email server

Below my settings and test
/Peter (Many thanks!)

haraka version: 2.5.0
node version: 0.10.29

[access.ini file] 
[check]
any=true
conn=true
helo=false
mail=false
rcpt=false

[access.domains file] 
127.0.0.1 (Does not blacklist ip-address)
!127.0.0.1 (Does not blacklist ip-address
domain.com (blacklists domain as expected
name@domain.com (whitelists emailaddress as expected)

[connect.rdns_access.blacklist file]
127.0.0.1 (Does blacklist ip-address)

[connect.rdns_access.whitelist file]
127.0.0.1 (Does not whitelist ip-address)

**Comment by msimerson** [comment]
Per the [access docs](https://haraka.github.io/manual/plugins/access.html), whitelist entries aren't exactly what you think. Sorry, that's a misnomer from the original plugin. The whitelists are merely, "not blacklisted" entries. So that when you blacklist 207.192, you can "unblacklist" 207.192.35.

As to using access.domains, you can't use IP addresses in there, that's why it's named .domains.

**Comment by msimerson** [comment]
PS: if you're trying to whitelist IPs so they can relay, you're looking for the [relay](https://haraka.github.io/manual/plugins/relay.html) plugin instead.
