### ISSUE TITLE
Error: Outbound email with "auth/flat_file" 

### ISSUE THREAD

**Issue by varmad** [baudehlo/Haraka#850]
=== Connected to localhost.
<-  220 li940-16 ESMTP Haraka 2.5.0 ready
 -> EHLO li940-16.members.linode.com
<-  250-li940-16 Hello ip6-localhost [::1], Haraka is at your service.
<-  250-PIPELINING
<-  250-8BITMIME
<-  250 SIZE 500000
*** Host did not advertise authentication
 -> QUIT
<-  221 li940-16 closing connection. Have a jolly good day.
=== Connection closed with remote host.

Please any one help me on this...

Thanks,
Varma

**Comment by smfreegard** [comment]
Varma,

As per the [docs](https://github.com/baudehlo/Haraka/blob/master/docs/plugins/auth/flat_file.md) - you must enable and use TLS before Haraka's authentication functions will be offered. 

If you use IPv4 loopback instead of IPv6; it will offer AUTH without TLS - I've just checked and we appear to be missing an exclusion for ::1.

Regards,
Steve.

**Comment by varmad** [comment]
Steve,

In which config file I need to enable TLS?

**Comment by smfreegard** [comment]
TLS is a plugin so you add it to config/plugins (e.g. echo tls >> config/plugins).   Then read the [plugin docs](https://github.com/baudehlo/Haraka/blob/master/docs/plugins/tls.md) on how to set it up.

**Comment by varmad** [comment]
Steve,

Thanks for your help, I enabled IPV4  and it is working.

Thanks,
Varma
